In [2]:
import numpy as np

# Creating arrays

### From list

In [3]:
a = np.array([1, 31, 2])
print(a)

[ 1 31  2]


In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a.dtype # the function array tries to infer the type

dtype('int64')

In [7]:
a = np.array([1, 31, 2.0])
a.dtype

dtype('float64')

### Multi-dimensional arrays

In [8]:
a = np.array([[1,3,2,5],[9,7,6,4]])
print(a)

[[1 3 2 5]
 [9 7 6 4]]


In [9]:
a.shape

(2, 4)

In [10]:
a.dtype

dtype('int64')

### Standard arrays

In [11]:
np.zeros(3) # array of 0s

array([ 0.,  0.,  0.])

In [12]:
np.zeros((3,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [13]:
np.zeros_like(a) # zero array with the dimensions of the array a

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
np.ones((3,3)) # array of 1s

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [15]:
np.eye(3) # identity matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [16]:
np.empty(3) # uninitialized arrays (should not assume anything about these values)

array([ 1.,  1.,  1.])

In [17]:
np.arange(8) # initialize array to a sequence

array([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
np.arange(1,10,2) # increments of two

array([1, 3, 5, 7, 9])

In [19]:
a.copy() # returns a copy of an array

array([[1, 3, 2, 5],
       [9, 7, 6, 4]])

# Data Types

### Numerics

In [20]:
np.array([1,3,2]).dtype

dtype('int64')

In [21]:
np.array([1,3,0],dtype="int8")

array([1, 3, 0], dtype=int8)

In [22]:
np.array([1,3,2],dtype="int64")

array([1, 3, 2])

In [23]:
b = np.array([1,3,2],dtype="float")
print(b)
print(b.dtype)

[ 1.  3.  2.]
float64


### Precision loss

In [24]:
0.1+0.2+0.3+0.3+0.1==1.0

False

In [25]:
np.isclose(0.1+0.2+0.3+0.3+0.1,1)

True

### Boolean

In [26]:
np.array([True, False, True])

array([ True, False,  True], dtype=bool)

In [27]:
np.array([1, 0, 1])

array([1, 0, 1])

In [28]:
np.array([1, 0, 1],dtype="bool")

array([ True, False,  True], dtype=bool)

### String

In [29]:
np.array(['hello', 'world'], dtype='string_')

array([b'hello', b'world'], 
      dtype='|S5')

In [30]:
np.array(['hello', 'world'], dtype='U')

array(['hello', 'world'], 
      dtype='<U5')

In [31]:
np.array(['hello', 'world', '和平'], dtype='string_') # expect an error

UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

In [32]:
np.array(['hello', 'world', '和平'], dtype='U')

array(['hello', 'world', '和平'], 
      dtype='<U5')

### Casting

In [33]:
string_array = np.array(['1.25', '-9.6'])

In [34]:
string_array

array(['1.25', '-9.6'], 
      dtype='<U4')

In [35]:
string_array.astype(np.float)

array([ 1.25, -9.6 ])

In [36]:
string_array.astype(np.float).astype(np.int)

array([ 1, -9])

# Vectorized Operations

In [4]:
a = np.array([-1,0,1])
b = np.array([4,5,6])

### Operation between arrays

In [5]:
a+b

array([3, 5, 7])

In [6]:
a*b

array([-4,  0,  6])

In [7]:
a-b

array([-5, -5, -5])

### Operations with scalars

In [8]:
a+2

array([1, 2, 3])

In [9]:
a*2

array([-2,  0,  2])

In [23]:
a**2

array([1, 0, 1])

In [13]:
a

array([-1,  0,  1])

In [14]:
2/a

/Users/Qingyuan/Applications/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([ -2.,  inf,   2.])

In [15]:
-2/a

/Users/Qingyuan/Applications/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([  2., -inf,  -2.])

In [16]:
np.sqrt(a)

/Users/Qingyuan/Applications/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


array([ nan,   0.,   1.])

In [17]:
np.inf

inf

In [18]:
# test for inf
print(np.isinf(np.inf))
print(np.isinf(-np.inf))
print(np.isinf(np.nan))
print(np.isinf(1))

True
True
False
False


In [19]:
# test for nan
print(np.isnan(np.inf))
print(np.isnan(-np.inf))
print(np.isnan(np.nan))
print(np.isnan(1))

False
False
True
False


In [20]:
# test for finiteness (not inf nor nan)
print(np.isfinite(np.inf))
print(np.isfinite(-np.inf))
print(np.isfinite(np.nan))
print(np.isfinite(1))

False
False
False
True


In [21]:
# disable warnings
import warnings
warnings.filterwarnings('ignore')
#warnings.filterwarnings('default') # enable warnings

### Math

In [25]:
a = np.array([1,3,4,2,1])

In [ ]:
a.max() # value of the maximal element

In [ ]:
a.min() # value of minimal element

In [ ]:
a.mean() # average

In [ ]:
a.std() # standard deviation

In [ ]:
a.sum() # sum elements

In [26]:
a.prod() # product of array's elements

24

In [27]:
print(a)
a.argmax() # first index of the maximal element

[1 3 4 2 1]


2

In [28]:
a.argmin() # first index of the smallest element

0

In [29]:
distribution = np.array([0.1, 0.2, 0.3, 0.3, 0.1]) # initialize probability distribution function

In [30]:
distribution.cumsum() # return the cumulative distribution function

array([ 0.1,  0.3,  0.6,  0.9,  1. ])

In [33]:
distribution.cumprod() # return the product of elements

array([ 0.1    ,  0.02   ,  0.006  ,  0.0018 ,  0.00018])

In [ ]:
a

In [ ]:
# other math operations
a = np.array([-1,2,0])
print('absolute value', np.abs(a))
print('sign', np.sign(a))

### Boolean arrays

In [ ]:
b1 = np.array([True, False, False])
b2 = np.array([True, False, True])

In [ ]:
a=1
if a<10 and a>0:
    print('a satisfies condition')
else:
    print('a does not satisfy condition')

In [ ]:
b1 & b2 # in Python we use 'and'

In [ ]:
b1 | b2

In [ ]:
~b1

In [ ]:
b1==b2

In [ ]:
(b1==b2).all() # test if all array values are True

In [ ]:
(b1==b2).any() # test if all there exists a True value in array

In [ ]:
a = np.array([1,2,5])
a==2

In [ ]:
a<3

In [36]:
# test if two arrays are equal
np.array([1,2,3])==[1,2,3]

array([ True,  True,  True], dtype=bool)

In [34]:
# '==' returns a vector
(np.array([1,2,3])==[1,2,3]).all()

True

In [42]:
np.array_equal(np.array([1,2,3]),[1,2,3])

True

In [43]:
a = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [44]:
a%3==0

array([[False, False,  True, False],
       [False,  True, False, False],
       [False, False,  True, False]], dtype=bool)

In [59]:
np.where(a%3==1, 1, 2)

array([1, 2, 2, 1, 2, 1])

### * Set operations

In [47]:
a = np.array([1,3,2,1,2,4])
b = [2,5]

In [48]:
np.unique(a)

array([1, 2, 3, 4])

In [49]:
np.intersect1d(a,b)

array([2])

In [50]:
np.union1d(a,b)

array([1, 2, 3, 4, 5])

In [51]:
np.in1d(a,b)

array([False, False,  True, False,  True, False], dtype=bool)

In [52]:
np.setdiff1d(a,b)

array([1, 3, 4])

# Exercise 1: array operations 
1. Create array holding the first 10 numbers in the Fibonaci series (https://en.wikipedia.org/wiki/Fibonacci_number)
2. Create array with the squared values of each number in the series
3. Create array specifying whether each number in the series is even

In [77]:
# write solution here
def fib(n):
    if(n == 1):
        return np.array([1])
    if(n == 2):
        return np.array([1,1])
    else:
        f = [1,1]
        for i in range(n-2):
            f.append(f[-1]+f[-2])
        x = np.array(f)
        return x
fib(8)

array([ 1,  1,  2,  3,  5,  8, 13, 21])

<br style=margin:500px;>
___

In [61]:
# solution to 1
f = [1,1] # first two elements of the Fibonaci series
for i in range(8):
    f.append(f[-1]+f[-2])
x=np.array(f)
x

array([ 1,  1,  2,  3,  5,  8, 13, 21, 34, 55])

In [62]:
# solution to 2
x**2

array([   1,    1,    4,    9,   25,   64,  169,  441, 1156, 3025])

In [63]:
# solution to 3
x%2==0

array([False, False,  True, False, False,  True, False, False,  True, False], dtype=bool)

# Indexing

In [42]:
a = np.array([10,20,30,40])

In [43]:
a[0]

10

In [44]:
a[1]

20

In [45]:
a[-1]

40

In [46]:
a[1:3]

array([20, 30])

### Basic Slicing and Indexing

In [47]:
a = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [48]:
a[0,:] # row 0

array([1, 2, 3, 4])

In [49]:
a[-1,:] # last row

array([10, 11, 12, 13])

In [50]:
a[:,1] # column 1

array([ 2,  6, 11])

In [72]:
b = a[1:3,0:4:4] # b is a view
b

array([[ 5],
       [10]])

In [52]:
b.shape

(2, 2)

In [64]:
b[0,0]=5 # b is a view, changes in b affect a

In [54]:
a 

array([[  1,   2,   3,   4],
       [999,   6,   7,   8],
       [ 10,  11,  12,  13]])

### Integer array indexing

In [64]:
a = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [65]:
a[[1],:] # row 1 (copy)

array([[5, 6, 7, 8]])

In [66]:
a[[-1],:] # last row

array([[10, 11, 12, 13]])

In [67]:
a[:,[2,3]] # columns 2,3

array([[ 3,  4],
       [ 7,  8],
       [12, 13]])

In [68]:
a[:,[3,2]] # column 3 and then 2

array([[ 4,  3],
       [ 8,  7],
       [13, 12]])

In [69]:
a[[0,1],[3,2]] # values in coordinates (0,3) and (1,2) - careful! returns 2 elements rather than 4

array([4, 7])

In [70]:
a[np.ix_([0,1],[3,2])] # to return all elements that are in rows 0,1 and columns 3,2

array([[4, 3],
       [8, 7]])

In [71]:
# setting values
a[:,[3,2]] = 999
a

array([[  1,   2, 999, 999],
       [  5,   6, 999, 999],
       [ 10,  11, 999, 999]])

### Boolean array indexing

In [80]:
a = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [81]:
a%3==0 # numbers with no remainder after division by 3

array([[False, False,  True, False],
       [False,  True, False, False],
       [False, False,  True, False]], dtype=bool)

In [82]:
a[a%3==0] # row major

array([ 3,  6, 12])

In [83]:
x = a[a%3==0] # x is a copy, changing x will not change a
print(x)

[ 3  6 12]


In [84]:
# setting values
a[a%3==0]=999
print(a)

[[  1   2 999   4]
 [  5 999   7   8]
 [ 10  11 999  13]]


In [85]:
# multiple conditions
a = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
a[(a%2==0)&(a>=4)]

array([ 4,  6,  8, 10, 12])

### Multi-dimensional arrays

In [77]:
a = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [78]:
a.sum()

82

In [79]:
a.sum(axis=0) # eliminates axis 0 by summing rows

array([16, 19, 22, 25])

In [84]:
a.sum(axis=1) # eliminates axis 1 by summing columns

array([10, 26, 46])

In [ ]:
a.std(axis=0) # compute standard deviation of each column

In [ ]:
a.std(axis=1) # compute the standard deviation of each row

# Exercise 2: Indexing 
A [magic square](https://en.wikipedia.org/wiki/Magic_square) is a matrix of distinct values, in which the sum of every row, column and main diagnoal are equal: 

<table class="wikitable" style="margin-left:auto;margin-right:auto;text-align:center;width:6em;height:6em;table-layout:fixed;">
<tr>
<td>4</td>
<td>9</td>
<td>2</td>
</tr>
<tr>
<td>3</td>
<td>5</td>
<td>7</td>
</tr>
<tr>
<td>8</td>
<td>1</td>
<td>6</td>
</tr>
</table>

1. Create a two dimensional array holding the magic square above
2. Compute the sum of the first row
1. Compute the sum of all rows
2. Compute the sum of all column 
3. Compute the sum of both diagonal
4. Write a function that receives a matrix and tests if it is a magic square 
5. Test your function the your initialized matrix and on np.zeros((3,3))


In [93]:
# write solution here
x = np.array([[4,9,2],[3,5,7],[8,1,6]])
print(x)
print(np.sum(x[0,:]))
print(np.sum(x,axis = 0))
print(np.sum(x,axis = 1))
print(np.sum(x[range(3),range(3)]))



[[4 9 2]
 [3 5 7]
 [8 1 6]]
15
[15 15 15]
[15 15 15]
15


<br style=margin:500px;>
___

In [ ]:
# solution to 1
x = np.array([[4, 9, 2],[3, 5, 7],[8, 1, 6]])
print(x)

# solution to 2,3
print('sum of each row', np.sum(x,axis=1))

# solution to 4
print('sum of each column', np.sum(x,axis=0))

# solution to 5
print('sum of primary diagonal', np.sum(x[range(3),range(3)]))

print('sum of secondary diagonal', np.sum(x[[0,1,2],[2,1,0]]))

In [ ]:
# solution to 6,7
def test_magic(m):
    d = m.shape[0]
    s = np.sum(m[0]) 
    return ((np.sum(m,axis=0)==s).all() and
            (np.sum(m,axis=1)==s).all() and
            (np.sum(m[range(d),range(d)])==s).all() and
            (np.sum(m[range(d),range(d-1,-1,-1)])==s).all() and
            ((np.unique(m))==np.arange(1,np.prod(m.shape)+1)).all())

print(test_magic(np.zeros((3,3))))
print(test_magic(x))

# * Math packages

### Linear algebra

In [86]:
a = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [87]:
a.T # transpose matrix

array([[ 1,  5, 10],
       [ 2,  6, 11],
       [ 3,  7, 12],
       [ 4,  8, 13]])

In [88]:
a.transpose((1,0))

array([[ 1,  5, 10],
       [ 2,  6, 11],
       [ 3,  7, 12],
       [ 4,  8, 13]])

In [89]:
a = np.array([[1,2,3],[4,5,6]]) # 2 by 3 matrix
b = np.array([1,1,1]) # 3 by 1 matrix
print(a,b)
np.dot(a,b) # matrix multiplication

[[1 2 3]
 [4 5 6]] [1 1 1]


array([ 6, 15])

### Probability

In [90]:
# random variables from the uniform distribution
np.random.rand(3,2)

array([[ 0.5062246 ,  0.09831073],
       [ 0.86586044,  0.00702056],
       [ 0.8314772 ,  0.43235019]])

In [91]:
# random variables from the standard normal distribution
np.random.randn(3,2)

array([[-0.55543834,  0.19035076],
       [-1.12177672,  1.35938168],
       [-0.21881169,  0.4178471 ]])

In [92]:
# random value from a set of values
for i in range(5):
    print(np.random.choice([1,-2,6,9]))

1
9
6
-2
9


In [93]:
# generate random permutations
for i in range(5):
    print(np.random.permutation([1,2,3,4,5]))

[2 3 4 1 5]
[5 4 1 3 2]
[2 1 4 5 3]
[5 4 1 2 3]
[5 2 1 3 4]


In [94]:
# shuffle sequence (inplace)
l = [1,2,3,4,5]
np.random.shuffle(l)
print(l)

[3, 4, 5, 2, 1]


In [95]:
# control for seed value (generate two random vectors)
print('First random list',np.random.rand(5))
print('Second random list',np.random.rand(5))

First random list [ 0.73031567  0.88534824  0.23362142  0.30545816  0.09997112]
Second random list [ 0.19598304  0.6312915   0.71771542  0.61941009  0.70536352]


In [96]:
# control for seed value (generate two identical vectors)
np.random.seed(8)
print('First random list',np.random.rand(5))
np.random.seed(8)
print('Second random list',np.random.rand(5))

First random list [ 0.8734294   0.96854066  0.86919454  0.53085569  0.23272833]
Second random list [ 0.8734294   0.96854066  0.86919454  0.53085569  0.23272833]


# Array manipulation

### Reshape

In [97]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [98]:
a.reshape((3,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [99]:
a.reshape((3,8),order='f')

array([[ 0,  3,  6,  9, 12, 15, 18, 21],
       [ 1,  4,  7, 10, 13, 16, 19, 22],
       [ 2,  5,  8, 11, 14, 17, 20, 23]])

In [100]:
b = a.reshape((4,6))
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [101]:
b.flatten() # default order is row-major

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [102]:
b.flatten(order='f') # order by columns

array([ 0,  6, 12, 18,  1,  7, 13, 19,  2,  8, 14, 20,  3,  9, 15, 21,  4,
       10, 16, 22,  5, 11, 17, 23])

In [103]:
b.ravel() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Concatenation

In [104]:
a = np.arange(12).reshape((3,4))
b = a + 20
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [105]:
np.concatenate((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [106]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  3, 20, 21, 22, 23],
       [ 4,  5,  6,  7, 24, 25, 26, 27],
       [ 8,  9, 10, 11, 28, 29, 30, 31]])

In [107]:
np.vstack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [108]:
np.hstack((a,b))

array([[ 0,  1,  2,  3, 20, 21, 22, 23],
       [ 4,  5,  6,  7, 24, 25, 26, 27],
       [ 8,  9, 10, 11, 28, 29, 30, 31]])

In [ ]:
c = np.array([9,9,9])
np.hstack((a,c)) # expect an error

In [ ]:
print(a.shape, c.shape)

In [ ]:
print(a.shape, c.reshape((3,1)).shape)

In [ ]:
np.hstack((a,c.reshape((3,1))))

### Splitting

In [109]:
a = np.arange(24).reshape((4,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [110]:
# splits the array to 2 arrays by rows (axis=0), returns list of arrays
for x in np.split(a,2,axis=0):
    print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [111]:
# splits a to 2 arrays by columns (axis=1)
for x in np.split(a,2,axis=1):
    print(x)

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]]
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]]


In [112]:
# try to split a to 4 arrays by columns (axis=1)
np.split(a,4,axis=1) # expect error

ValueError: array split does not result in an equal division

In [113]:
# split a by columns at columns 3 and 4
for x in np.split(a,[3,4],axis=1):
    print(x)

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]]
[[ 3]
 [ 9]
 [15]
 [21]]
[[ 4  5]
 [10 11]
 [16 17]
 [22 23]]


### Broadcasting

In [114]:
a = np.arange(4)
b = np.arange(4)*2
print('a:',a)
print('b:',b)

a: [0 1 2 3]
b: [0 2 4 6]


In [ ]:
a+b

In [ ]:
a + 1

In [ ]:
c = np.arange(12).reshape((3,4))
c

In [ ]:
c + np.array([-1,-2,-3,-4])

In [ ]:
c + np.array([-1,-2,-3]) # expect error

In [ ]:
c + np.array([-1,-2,-3]).reshape((3,1))